platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

target 'RxWebRTC_Example' do
  pod 'RxWebRTC', :path => '../'
  pod 'GoogleWebRTC', '1.1.28117'
  pod 'RxSwift', '5.0.0'
  pod 'RxCocoa', '5.0.0'

  target 'RxWebRTC_Tests' do
    inherit! :search_paths
    pod 'Nimble', '8.0.2'
    pod 'Quick', '2.1.0'
  end
end
